# Generated by Django 3.1.3 on 2021-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0003_producto_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_producto',
            options={'verbose_name': 'Categoria_Producto', 'verbose_name_plural': 'Categorias_Producto'},
        ),
        migrations.AddField(
            model_name='producto',
            name='contenido',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
